---
jobs:
- name: deploy
  plan:
  - get: docker-image
    trigger: true
  - aggregate:
    - get: source
    - get: helm-values
  - put: helm-release
    params:
      chart: mojanalytics/cpanel
      values:
      - helm-values/chart-env-config/dev/cpanel.yml
      override_values:
      - { key: image.tag, path: source/.git/ref }
      - { key: branch, value: main }
      - { key: tags.branch, value: false }

resources:
- name: docker-image
  type: docker-image
  source:
    tag: main
    repository: quay.io/mojanalytics/control-panel
    username: ((quay.username))
    password: ((quay.password))

- name: helm-values
  type: git
  source:
    git_crypt_key: ((gitcrypt-keys.config))
    uri: https://github.com/ministryofjustice/analytics-platform-config.git

- name: helm-release
  type: helm
  source:
    cluster_url: ((kubernetes.api-url))
    cluster_ca: ((kubernetes.ca-cert))
    helm_host: tiller-deploy.kube-system:44134
    token: ((kubernetes.token))
    namespace: default
    release: cpanel-main
    repos:
    - name: mojanalytics
      url: http://moj-analytics-helm-repo.s3-website-eu-west-1.amazonaws.com

- name: source
  type: git
  source:
    uri: https://github.com/ministryofjustice/analytics-platform-control-panel.git
    branch: main

resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: 2.13.1
